# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: poetry run -C backend/app -- black
    language: system
    types: [python]
  - id: autoflake
    name: autoflake
    entry: poetry run -C backend/app -- autoflake
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: poetry run  -C backend/app -- flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]

  - id: ruff
    name: Format with Ruff
    entry: poetry run -C backend/app -- ruff
    language: system
    types: [python]
    args: [--fix, --exit-non-zero-on-fix, --no-cache]

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
