version: "3.3"
services:
  db:
    container_name: bemore-db
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default

  pgadmin:
    container_name: bemore-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8089:5050"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - default

  queue:
    container_name: bemore-queue
    image: rabbitmq:3
    # Using the below image instead is required to enable the "Broker" tab in the flower UI:
    # image: rabbitmq:3-management
    #
    # You also have to change the flower command

  flower:
    container_name: bemore-flower
    image: mher/flower
    depends_on:
      - queue
    command: celery --broker=amqp://guest:guest@bemore-queue:5672// flower --port=5555
    ports:
      - "5555:5555"

  backend:
    container_name: bemore-backend
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - "8000:8001"
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - ./backend/app:/app

  celeryworker:
    container_name: bemore-celeryworker
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - queue
    env_file:
      - .env
    environment:
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST?Variable not set}
    build:
      context: ./backend
      dockerfile: celeryworker.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}


volumes:
  app-db-data:
