name: Testing bemore

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo snap install --edge --classic just
    - uses: actions/checkout@v4
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.3.7
      with:
        key: docker-${{ hashFiles('docker-compose.ci.yml') }}
    - run: just test
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        directory: ./backend/app/
        fail_ci_if_error: true
        verbose: true
